version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
    # Chalk v5 is ESM only
    - dependency-name: "chalk"
      update-types: ["version-update:semver-major"]
